name: Deploy to main branch

on:
  push:
    branches:
      - main

jobs:
  call-template-workflow:
    uses: ./.github/workflows/template-workflow.yml
    with:
      stage: prod
      region: us-east-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
